# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 830)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 830))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1440, 810))
        self.centralwidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setMinimumSize(QtCore.QSize(1440, 810))
        self.frame_main.setMaximumSize(QtCore.QSize(2560, 1440))
        self.frame_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_main.setStyleSheet("#frame_main\n"
"{\n"
"    background-color: #ffffff;\n"
"    border:1px solid #161A1E;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    padding:2px 4px;\n"
"    border:0px;\n"
"}\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_main)
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_title.setStyleSheet("border:0px;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_2.setContentsMargins(20, 0, 3, 0)
        self.gridLayout_2.setSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_close.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_close.setStyleSheet("#pushButton_close\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_close:hover\n"
"{ \n"
"    background: #cccccc; \n"
"    border-color: #cccccc;\n"
"}")
        self.pushButton_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_minimize = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_minimize.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_minimize.setStyleSheet("#pushButton_minimize\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_minimize:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minimize.setIcon(icon1)
        self.pushButton_minimize.setCheckable(True)
        self.pushButton_minimize.setAutoExclusive(True)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.gridLayout_2.addWidget(self.pushButton_minimize, 0, 2, 1, 1)
        self.pushButton_normal = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_normal.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_normal.setStyleSheet("#pushButton_normal\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_normal:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_normal.setIcon(icon2)
        self.pushButton_normal.setCheckable(True)
        self.pushButton_normal.setChecked(False)
        self.pushButton_normal.setAutoExclusive(True)
        self.pushButton_normal.setObjectName("pushButton_normal")
        self.gridLayout_2.addWidget(self.pushButton_normal, 0, 3, 1, 1)
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.line = QtWidgets.QFrame(self.frame_main)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame_content = QtWidgets.QFrame(self.frame_main)
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_show = QtWidgets.QFrame(self.frame_content)
        self.frame_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_show.setStyleSheet("")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_show)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_left_aside = QtWidgets.QFrame(self.frame_show)
        self.frame_left_aside.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_left_aside.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_left_aside.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_aside.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_aside.setObjectName("frame_left_aside")
        self.formLayout = QtWidgets.QFormLayout(self.frame_left_aside)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_left_aside)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.frame_input_type = QtWidgets.QFrame(self.frame_left_aside)
        self.frame_input_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_input_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_type.setObjectName("frame_input_type")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_input_type)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_image = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_image.setStyleSheet("#pushButton_image\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_image:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_image.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/image-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_image.setIcon(icon3)
        self.pushButton_image.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_image.setCheckable(True)
        self.pushButton_image.setAutoExclusive(True)
        self.pushButton_image.setObjectName("pushButton_image")
        self.horizontalLayout_3.addWidget(self.pushButton_image)
        self.pushButton_video = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_video.setStyleSheet("#pushButton_video\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_video:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_video.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/media.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video.setIcon(icon4)
        self.pushButton_video.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_video.setObjectName("pushButton_video")
        self.horizontalLayout_3.addWidget(self.pushButton_video)
        self.pushButton_camera = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_camera.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_camera.setStyleSheet("#pushButton_camera\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_camera:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_camera.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/industry-safety.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_camera.setIcon(icon5)
        self.pushButton_camera.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.horizontalLayout_3.addWidget(self.pushButton_camera)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_input_type)
        self.label_3 = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_model = QtWidgets.QComboBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_model.setFont(font)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_model)
        self.label_5 = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_6 = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_7 = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_8 = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_left_aside)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 245, 233))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.scrollArea)
        self.label_2 = QtWidgets.QLabel(self.frame_left_aside)
        self.label_2.setMaximumSize(QtCore.QSize(172, 60))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("image: url(:/image/image/logo.png);\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"")
        self.label_2.setLineWidth(1)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap(":/image/image/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_9 = QtWidgets.QLabel(self.frame_left_aside)
        self.label_9.setMinimumSize(QtCore.QSize(0, 60))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_3.addWidget(self.frame_left_aside, 0, 0, 2, 1)
        self.frame = QtWidgets.QFrame(self.frame_show)
        self.frame.setMinimumSize(QtCore.QSize(1170, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setStyleSheet("#splitter::handle{\n"
"    background: 2px solid #cccccc;\n"
"}")
        self.splitter.setLineWidth(10)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.label_origin = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_origin.sizePolicy().hasHeightForWidth())
        self.label_origin.setSizePolicy(sizePolicy)
        self.label_origin.setMinimumSize(QtCore.QSize(200, 0))
        self.label_origin.setStyleSheet("border:1px solid #CCCCCC;\n"
"border-radius:10px;")
        self.label_origin.setText("")
        self.label_origin.setScaledContents(False)
        self.label_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_origin.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_origin.setObjectName("label_origin")
        self.label_detect = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_detect.sizePolicy().hasHeightForWidth())
        self.label_detect.setSizePolicy(sizePolicy)
        self.label_detect.setMinimumSize(QtCore.QSize(200, 0))
        self.label_detect.setStyleSheet("border:1px solid #CCCCCC;\n"
"border-radius:10px;")
        self.label_detect.setText("")
        self.label_detect.setScaledContents(False)
        self.label_detect.setAlignment(QtCore.Qt.AlignCenter)
        self.label_detect.setObjectName("label_detect")
        self.horizontalLayout.addWidget(self.splitter)
        self.gridLayout_3.addWidget(self.frame, 0, 2, 1, 1)
        self.frame_progress_bar = QtWidgets.QFrame(self.frame_show)
        self.frame_progress_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_progress_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_progress_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_progress_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progress_bar.setObjectName("frame_progress_bar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_progress_bar)
        self.gridLayout_4.setContentsMargins(3, 1, 3, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_play = QtWidgets.QPushButton(self.frame_progress_bar)
        self.pushButton_play.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play.setStyleSheet("#pushButton_play\n"
"{\n"
"    border-radius:20px\n"
"}\n"
"#pushButton_play:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_play.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play.setIcon(icon6)
        self.pushButton_play.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_play.setObjectName("pushButton_play")
        self.gridLayout_4.addWidget(self.pushButton_play, 0, 0, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_progress_bar)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setAutoFillBackground(False)
        self.pushButton_stop.setStyleSheet("#pushButton_stop\n"
"{\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_stop:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_stop.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon7)
        self.pushButton_stop.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_4.addWidget(self.pushButton_stop, 0, 3, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_progress_bar)
        self.horizontalSlider.setStyleSheet("QSlider::sub-page:horizontal \n"
"{\n"
"    background: rgb(90,49,255);\n"
"    border-radius: 2px;\n"
"    margin-top:8px;\n"
"    margin-bottom:8px;\n"
"}\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background: rgb(255,255, 255);\n"
"    border: 0px solid #777;\n"
"    border-radius: 2px;\n"
"    margin-top:9px;\n"
"    margin-bottom:9px;\n"
"}\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: rgb(193,204,208);\n"
"    width: 5px;\n"
"    border: 1px solid rgb(193,204,208);\n"
"    border-radius: 2px; \n"
"    margin-top:6px;\n"
"    margin-bottom:6px;\n"
"}\n"
"QSlider::handle:horizontal:hover\n"
"{\n"
"    background: rgb(193,204,208);\n"
"    width: 10px;\n"
"    border: 1px solid rgb(193,204,208);\n"
"    border-radius: 5px; \n"
"    margin-top:4px;\n"
"    margin-bottom:4px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 0, 1, 1, 2)
        self.gridLayout_3.addWidget(self.frame_progress_bar, 1, 1, 1, 3)
        self.horizontalLayout_2.addWidget(self.frame_show)
        self.verticalLayout_2.addWidget(self.frame_content)
        self.line_2 = QtWidgets.QFrame(self.frame_main)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(1440, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.statusBar.setFont(font)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("background-color:  #FFFFFF;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"padding:2px 4px;\n"
"border:0px;\n"
"padding-left:20px\n"
"")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "yolov5安全距离检测系统"))
        self.label_4.setText(_translate("MainWindow", "输入"))
        self.label_3.setText(_translate("MainWindow", "模型"))
        self.comboBox_model.setItemText(0, _translate("MainWindow", "yolov5s.pt"))
        self.comboBox_model.setItemText(1, _translate("MainWindow", "best.pt"))
        self.label_5.setText(_translate("MainWindow", "置信"))
        self.label_6.setText(_translate("MainWindow", "IOU"))
        self.label_7.setText(_translate("MainWindow", "延迟"))
        self.label_8.setText(_translate("MainWindow", "检测结果"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "设置"))
from resource import icon_rc
from resource import image_rc
