# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 810)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 810))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1440, 810))
        self.centralwidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 1440, 810))
        self.frame_main.setMinimumSize(QtCore.QSize(1440, 810))
        self.frame_main.setMaximumSize(QtCore.QSize(2560, 1440))
        self.frame_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_main.setStyleSheet("background-color: #ffffff;\n"
"border:1px solid #161A1E;\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_main)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_minimize = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.horizontalLayout.addWidget(self.pushButton_minimize)
        self.pushButton_normal = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_normal.setObjectName("pushButton_normal")
        self.horizontalLayout.addWidget(self.pushButton_normal)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_close.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame_content = QtWidgets.QFrame(self.frame_main)
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_asid = QtWidgets.QFrame(self.frame_content)
        self.frame_left_asid.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"border-radius:10px;\n"
"")
        self.frame_left_asid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_asid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_asid.setObjectName("frame_left_asid")
        self.horizontalLayout_2.addWidget(self.frame_left_asid)
        self.frame_show = QtWidgets.QFrame(self.frame_content)
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.horizontalLayout_2.addWidget(self.frame_show)
        self.verticalLayout_2.addWidget(self.frame_content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_minimize.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_normal.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_close.setText(_translate("MainWindow", "PushButton"))
