# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 830)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 830))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1440, 810))
        self.centralwidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setMinimumSize(QtCore.QSize(1440, 810))
        self.frame_main.setMaximumSize(QtCore.QSize(2560, 1440))
        self.frame_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_main.setStyleSheet("#frame_main\n"
"{\n"
"    background-color: #ffffff;\n"
"    border:1px solid #161A1E;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    padding:2px 4px;\n"
"    border:0px;\n"
"}\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_main)
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_title.setStyleSheet("border:0px;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_2.setContentsMargins(20, 0, 3, 0)
        self.gridLayout_2.setSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_close.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_close.setStyleSheet("#pushButton_close\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_close:hover\n"
"{ \n"
"    background: #cccccc; \n"
"    border-color: #cccccc;\n"
"}")
        self.pushButton_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_minimize = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_minimize.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_minimize.setStyleSheet("#pushButton_minimize\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_minimize:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minimize.setIcon(icon1)
        self.pushButton_minimize.setCheckable(True)
        self.pushButton_minimize.setAutoExclusive(True)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.gridLayout_2.addWidget(self.pushButton_minimize, 0, 2, 1, 1)
        self.pushButton_normal = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_normal.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_normal.setStyleSheet("#pushButton_normal\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_normal:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_normal.setIcon(icon2)
        self.pushButton_normal.setCheckable(True)
        self.pushButton_normal.setChecked(False)
        self.pushButton_normal.setAutoExclusive(True)
        self.pushButton_normal.setObjectName("pushButton_normal")
        self.gridLayout_2.addWidget(self.pushButton_normal, 0, 3, 1, 1)
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.line_top = QtWidgets.QFrame(self.frame_main)
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_top.setObjectName("line_top")
        self.verticalLayout_2.addWidget(self.line_top)
        self.frame_content = QtWidgets.QFrame(self.frame_main)
        self.frame_content.setMinimumSize(QtCore.QSize(1440, 0))
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_show = QtWidgets.QFrame(self.frame_content)
        self.frame_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_show.setStyleSheet("")
        self.frame_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_show)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_left_aside = QtWidgets.QFrame(self.frame_show)
        self.frame_left_aside.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_left_aside.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_left_aside.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_aside.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_aside.setObjectName("frame_left_aside")
        self.formLayout = QtWidgets.QFormLayout(self.frame_left_aside)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_setting = QtWidgets.QLabel(self.frame_left_aside)
        self.label_setting.setMinimumSize(QtCore.QSize(0, 60))
        self.label_setting.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_setting.setFont(font)
        self.label_setting.setScaledContents(True)
        self.label_setting.setObjectName("label_setting")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_setting)
        self.label_logo = QtWidgets.QLabel(self.frame_left_aside)
        self.label_logo.setMaximumSize(QtCore.QSize(172, 60))
        self.label_logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_logo.setStyleSheet("image: url(:/image/image/logo.png);\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"")
        self.label_logo.setLineWidth(1)
        self.label_logo.setText("")
        self.label_logo.setTextFormat(QtCore.Qt.AutoText)
        self.label_logo.setPixmap(QtGui.QPixmap(":/image/image/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setWordWrap(False)
        self.label_logo.setIndent(-1)
        self.label_logo.setOpenExternalLinks(False)
        self.label_logo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_logo.setObjectName("label_logo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_logo)
        self.label_inpuy = QtWidgets.QLabel(self.frame_left_aside)
        self.label_inpuy.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_inpuy.setFont(font)
        self.label_inpuy.setObjectName("label_inpuy")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_inpuy)
        self.frame_input_type = QtWidgets.QFrame(self.frame_left_aside)
        self.frame_input_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_input_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_type.setObjectName("frame_input_type")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_input_type)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_image = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_image.setStyleSheet("#pushButton_image\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_image:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_image.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/image-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_image.setIcon(icon3)
        self.pushButton_image.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_image.setCheckable(True)
        self.pushButton_image.setAutoExclusive(True)
        self.pushButton_image.setObjectName("pushButton_image")
        self.horizontalLayout_3.addWidget(self.pushButton_image)
        self.pushButton_video = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_video.setStyleSheet("#pushButton_video\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_video:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_video.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/media.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_video.setIcon(icon4)
        self.pushButton_video.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_video.setObjectName("pushButton_video")
        self.horizontalLayout_3.addWidget(self.pushButton_video)
        self.pushButton_camera = QtWidgets.QPushButton(self.frame_input_type)
        self.pushButton_camera.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_camera.setStyleSheet("#pushButton_camera\n"
"{\n"
"    border:0px;\n"
"}\n"
"#pushButton_camera:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_camera.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/industry-safety.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_camera.setIcon(icon5)
        self.pushButton_camera.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.horizontalLayout_3.addWidget(self.pushButton_camera)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_input_type)
        self.label_model = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_model.setFont(font)
        self.label_model.setObjectName("label_model")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_model)
        self.comboBox_model = QtWidgets.QComboBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_model.setFont(font)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_model)
        self.label_confid = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_confid.setFont(font)
        self.label_confid.setObjectName("label_confid")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_confid)
        self.spinBox_confiden = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_confiden.setFont(font)
        self.spinBox_confiden.setObjectName("spinBox_confiden")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_confiden)
        self.label_IOU = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_IOU.setFont(font)
        self.label_IOU.setObjectName("label_IOU")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_IOU)
        self.spinBox_IOU = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_IOU.setFont(font)
        self.spinBox_IOU.setObjectName("spinBox_IOU")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_IOU)
        self.label_delay = QtWidgets.QLabel(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_delay.setFont(font)
        self.label_delay.setObjectName("label_delay")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_delay)
        self.spinBox_delay = QtWidgets.QSpinBox(self.frame_left_aside)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_delay.setFont(font)
        self.spinBox_delay.setObjectName("spinBox_delay")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_delay)
        self.label_answer = QtWidgets.QLabel(self.frame_left_aside)
        self.label_answer.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_answer.setFont(font)
        self.label_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_answer.setObjectName("label_answer")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_answer)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_left_aside)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 257, 451))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_answer = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.listWidget_answer.setFont(font)
        self.listWidget_answer.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget_answer.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_answer.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_answer.setMovement(QtWidgets.QListView.Static)
        self.listWidget_answer.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_answer.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_answer.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_answer.setObjectName("listWidget_answer")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_answer.addItem(item)
        self.horizontalLayout_4.addWidget(self.listWidget_answer)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.scrollArea)
        self.checkBox_auto_save = QtWidgets.QCheckBox(self.frame_left_aside)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_auto_save.sizePolicy().hasHeightForWidth())
        self.checkBox_auto_save.setSizePolicy(sizePolicy)
        self.checkBox_auto_save.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.checkBox_auto_save.setFont(font)
        self.checkBox_auto_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_auto_save.setAutoFillBackground(False)
        self.checkBox_auto_save.setStyleSheet("margin-left:28px")
        self.checkBox_auto_save.setObjectName("checkBox_auto_save")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox_auto_save)
        self.gridLayout_3.addWidget(self.frame_left_aside, 0, 0, 2, 1)
        self.frame_media = QtWidgets.QFrame(self.frame_show)
        self.frame_media.setMinimumSize(QtCore.QSize(1160, 0))
        self.frame_media.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_media.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_media.setObjectName("frame_media")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_media)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.frame_media)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setStyleSheet("#splitter::handle{\n"
"    background: 2px solid #cccccc;\n"
"}")
        self.splitter.setLineWidth(10)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.horizontalLayout.addWidget(self.splitter)
        self.gridLayout_3.addWidget(self.frame_media, 0, 2, 1, 1)
        self.frame_progress_bar = QtWidgets.QFrame(self.frame_show)
        self.frame_progress_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_progress_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_progress_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_progress_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progress_bar.setObjectName("frame_progress_bar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_progress_bar)
        self.gridLayout_4.setContentsMargins(3, 1, 3, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_progress_bar)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setAutoFillBackground(False)
        self.pushButton_stop.setStyleSheet("#pushButton_stop\n"
"{\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_stop:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_stop.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon6)
        self.pushButton_stop.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_4.addWidget(self.pushButton_stop, 0, 4, 1, 1)
        self.pushButton_play = QtWidgets.QPushButton(self.frame_progress_bar)
        self.pushButton_play.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play.setStyleSheet("#pushButton_play\n"
"{\n"
"    border-radius:20px\n"
"}\n"
"#pushButton_play:hover\n"
"{ \n"
"    background: #CCCCCC; \n"
"    border-color: #CCCCCC;\n"
"}")
        self.pushButton_play.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play.setIcon(icon7)
        self.pushButton_play.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_play.setObjectName("pushButton_play")
        self.gridLayout_4.addWidget(self.pushButton_play, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_progress_bar)
        self.horizontalSlider.setStyleSheet("QSlider::sub-page:horizontal \n"
"{\n"
"    background: rgb(90,49,255);\n"
"    border-radius: 2px;\n"
"    margin-top:8px;\n"
"    margin-bottom:8px;\n"
"}\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background: rgb(255,255, 255);\n"
"    border: 0px solid #777;\n"
"    border-radius: 2px;\n"
"    margin-top:9px;\n"
"    margin-bottom:9px;\n"
"}\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: rgb(193,204,208);\n"
"    width: 5px;\n"
"    border: 1px solid rgb(193,204,208);\n"
"    border-radius: 2px; \n"
"    margin-top:6px;\n"
"    margin-bottom:6px;\n"
"}\n"
"QSlider::handle:horizontal:hover\n"
"{\n"
"    background: rgb(193,204,208);\n"
"    width: 10px;\n"
"    border: 1px solid rgb(193,204,208);\n"
"    border-radius: 5px; \n"
"    margin-top:4px;\n"
"    margin-bottom:4px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_progress_bar, 1, 1, 1, 3)
        self.horizontalLayout_2.addWidget(self.frame_show)
        self.verticalLayout_2.addWidget(self.frame_content)
        self.line_bottom = QtWidgets.QFrame(self.frame_main)
        self.line_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.verticalLayout_2.addWidget(self.line_bottom)
        self.verticalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QtCore.QSize(1440, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.statusBar.setFont(font)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("background-color:  #FFFFFF;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border:0px;\n"
"")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "yolov5安全距离检测系统"))
        self.label_setting.setText(_translate("MainWindow", "设置"))
        self.label_inpuy.setText(_translate("MainWindow", "输入"))
        self.label_model.setText(_translate("MainWindow", "模型"))
        self.comboBox_model.setItemText(0, _translate("MainWindow", "yolov5s.pt"))
        self.comboBox_model.setItemText(1, _translate("MainWindow", "best.pt"))
        self.label_confid.setText(_translate("MainWindow", "置信"))
        self.label_IOU.setText(_translate("MainWindow", "IOU"))
        self.label_delay.setText(_translate("MainWindow", "延迟"))
        self.label_answer.setText(_translate("MainWindow", "检测结果"))
        __sortingEnabled = self.listWidget_answer.isSortingEnabled()
        self.listWidget_answer.setSortingEnabled(False)
        item = self.listWidget_answer.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(4)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(5)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(6)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(7)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(8)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(9)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(10)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(11)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(12)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(13)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(14)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_answer.item(15)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget_answer.setSortingEnabled(__sortingEnabled)
        self.checkBox_auto_save.setText(_translate("MainWindow", "自动保存结果"))
from resource import icon_rc
from resource import image_rc
